# service configuration for our database
#database:

  # use the preferred version of the official Postgres image
  # see https://hub.docker.com/_/postgres/
#  image: postgres:9.4.5

  # persist the database between containers by storing it in a volume
#  volumes:
#    - postgres-volume:/var/lib/postgresql/data

# service configuration for our dockerized PMB app
app:

  # use the Dockerfile next to this file
  build: .

  # makes the app container aware of the DB container
#  links:
#    - database

  # expose ionic's port
  ports:
    - "80:3001"
    - "8100:3002"
    
  # map our application source code, in full, to the application root of our container
  volumes:
    - node-volume:/home/pormibarrio/
    
  

